import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider, ProtectRoute } from "@/contexts/auth";
import "@uploadthing/react/styles.css";

import { SidebarProvider } from "@/components/ui/sidebar";
import { SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "VC Filling",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans">
        <AuthProvider>
          <SidebarProvider>
<main>
              <ProtectRoute>
                {children}
              </ProtectRoute>
            </main>
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
